package:
  name: fastmbar
  version: "0.0.4"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.1.0
    - pytorch >=1.0.0
    
  run:
    - python
    - numpy >=1.14.0
    - scipy >=1.1.0
    - pytorch >=1.0.0

about:
  home: https://github.com/xqding/FastMBAR
  license: MIT License
  summary: 'A fast solver for large scale MBAR/UWHAM equations'
  license_family: MIT
